name: telsavideo
description: Decentralized video sharing platform like tiktok.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  ffi: ^2.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  #google_mobile_ads: ^2.3.0
  #firebase_analytics: ^8.3.2
  #firebase_auth: ^1.2.0
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  oauth2: ^2.0.2
  font_awesome_flutter: ^9.2.0
  dio: ^5.4.0
  get: ^4.6.6
  url_launcher: ^6.2.2
  platform: ^3.1.3
  path_provider: ^2.1.1
  path_provider_platform_interface: ^2.1.1
  shared_preferences: ^2.2.2
  # network status
  connectivity: ^3.0.6
  modal_bottom_sheet: ^3.0.0-pre
  html: ^0.15.4
  uni_links: ^0.5.1
  flutter_custom_tabs: ^1.2.1
  modal_progress_hud_alt: ^1.0.0
  quiver: ^3.2.1
  video_player: ^2.8.1
  camera: ^0.10.5+5
  in_app_purchase: ^3.1.11
  package_info: ^2.0.2
  share: ^2.0.4
  #flutter_android_pip: ^0.0.2
  flutter_local_notifications: ^16.2.0
  pull_to_refresh: ^2.0.0
  permission_handler: ^11.1.0
  #open_file: ^3.2.1
  #flutter_downloader: ^1.7.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  timeago: ^3.6.0
  cupertino_icons: ^1.0.6
  flutter_html: ^3.0.0-beta.2
  chewie: ^1.7.4
  #flutter_ffmpeg: ^0.4.0
  in_app_update: ^4.2.2
  flutter_svg: ^2.0.9
  #http: ^0.13.3
  provider: ^6.1.1
  avatar_glow: any
  #getflutter: ^1.1.3
  getwidget: ^4.0.0
  #money_formatter: ^0.0.3
  dio_cookie_manager: ^3.1.1
  marquee: ^2.2.3
  marquee_widget: ^1.2.0
  like_button: ^2.0.5
  toast: ^0.3.0
  fluttertoast: ^8.2.4
  #upgrader: ^3.5.1
  carousel_pro_nullsafety: ^2.0.0
  flutter_switch: ^0.3.2
  flutter_spinkit: ^5.2.0
  libphonenumber: ^2.0.2
  flutter_inappwebview: ^5.8.0
  flutter_signin_button: ^2.0.0
  form_field_validator: ^1.1.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.7.0
  expandable: ^5.0.1
  sign_in_with_apple: ^5.0.0
  page_transition: ^2.1.0
  flutter_form_builder: ^9.1.1
  equatable: ^2.0.5
  flutter_custom_tabs_web: ^1.1.0
  #https://github.com/fluttercommunity/plus_plugins
  #device_info_plus: ^2.1.0
  sentry_flutter: ^7.13.2
  flutter_easyloading: ^3.0.5
  image_picker: ^1.0.5
  video_thumbnail: ^0.5.3
  package_info_plus: ^5.0.1
  http: ^1.1.2

dev_dependencies:
  stack_trace: ^1.11.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


flutter_icons:
  #android
  android: true
  image_path: "assets/dtok.png"
  adaptive_icon_background: "assets/appbackground.png" # only available for Android 8.0 devices and above
  #ios
  ios: true
  image_path_ios: "assets/dtok_ios.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/dtok_1.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/dtok_1.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/dtok_1.png"

module:
  androidX: true


# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true # Add this line
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/slider/
    - assets/dance/
    - assets/laugh/
    - assets/food/
    - assets/user_profile/
    - assets/user.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DouyinIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf
        # - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        # - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        #   weight: 600
        # - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        #   weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
