// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0gJgYQnL5Pn21ziasN5Ok1CMydcN0Lrw',
    appId: '1:165025931859:web:a10952bb49cb8557885ca6',
    messagingSenderId: '165025931859',
    projectId: 'dtok-438fb',
    authDomain: 'dtok-438fb.firebaseapp.com',
    databaseURL: 'https://dtok-438fb-default-rtdb.firebaseio.com',
    storageBucket: 'dtok-438fb.appspot.com',
    measurementId: 'G-PVZ1NQPVNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPfFgkhA5cATnmb2NOh5OVLL0q_6GGcE',
    appId: '1:165025931859:android:87fac465d66e4159885ca6',
    messagingSenderId: '165025931859',
    projectId: 'dtok-438fb',
    databaseURL: 'https://dtok-438fb-default-rtdb.firebaseio.com',
    storageBucket: 'dtok-438fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwQ2kWYjWYN0WYcyE_kECTawz6fFwuDG8',
    appId: '1:165025931859:ios:d58af5d1f3be01de885ca6',
    messagingSenderId: '165025931859',
    projectId: 'dtok-438fb',
    databaseURL: 'https://dtok-438fb-default-rtdb.firebaseio.com',
    storageBucket: 'dtok-438fb.appspot.com',
    androidClientId: '165025931859-l8npthdrgheseevn8furv4igl25patc3.apps.googleusercontent.com',
    iosClientId: '165025931859-bedkdidcimqn8lbtgpt8nqfl6v6alv5i.apps.googleusercontent.com',
    iosBundleId: 'com.tlsa.dtok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwQ2kWYjWYN0WYcyE_kECTawz6fFwuDG8',
    appId: '1:165025931859:ios:98663ecdd18b70d8885ca6',
    messagingSenderId: '165025931859',
    projectId: 'dtok-438fb',
    databaseURL: 'https://dtok-438fb-default-rtdb.firebaseio.com',
    storageBucket: 'dtok-438fb.appspot.com',
    androidClientId: '165025931859-l8npthdrgheseevn8furv4igl25patc3.apps.googleusercontent.com',
    iosClientId: '165025931859-gnd7eqh8h2bedkbqg1l1tju9kh247lmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.telsavideo',
  );
}
